// content-srd/src/index.ts
// Exports the SRD 5.2 content pack for Open20
//
// Runtime validation ensures the JSON data matches the ContentPack type.
// This eliminates the need for consumers to re-validate or re-transform
// the data (e.g., no more SchemaService.transformSpells() in spellbook).

import type { ContentPack } from 'open20-core/content';
import type { Spell } from 'open20-core';

// Import all SRD JSON data files
import metaJson from '../data/meta.json' with { type: 'json' };
import speciesJson from '../data/species.json' with { type: 'json' };
import backgroundsJson from '../data/backgrounds.json' with { type: 'json' };
import classesJson from '../data/classes.json' with { type: 'json' };
import subclassesJson from '../data/subclasses.json' with { type: 'json' };
import featsJson from '../data/feats.json' with { type: 'json' };
import weaponsJson from '../data/weapons.json' with { type: 'json' };
import armorJson from '../data/armor.json' with { type: 'json' };
import gearJson from '../data/gear.json' with { type: 'json' };
import spellsJsonRaw from '../data/spells.json' with { type: 'json' };
import monstersJson from '../data/monsters.json' with { type: 'json' };

// ── Spell normalisation ─────────────────────────────────────
// The JSON data is trusted (generated by our own parse scripts), but we
// still normalise a few fields to guarantee type-safety at runtime.

type RawSpell = Record<string, unknown>;

function normaliseSpells(raw: unknown): Spell[] {
  if (!Array.isArray(raw)) return [];
  return (raw as RawSpell[]).map((s, i): Spell => {
    const id = (s.id as string) || `spell-${i}`;
    const level = Math.max(0, Math.min(9, parseInt(String(s.level ?? 0)) || 0)) as Spell['level'];

    // components: string | string[] | Record → string[]
    let components: string[] = [];
    if (Array.isArray(s.components)) {
      components = (s.components as unknown[]).filter((c): c is string => typeof c === 'string');
    } else if (typeof s.components === 'string') {
      components = (s.components as string)
        .split(',')
        .map((c) => c.trim())
        .filter(Boolean);
    } else if (typeof s.components === 'object' && s.components !== null) {
      components = Object.keys(s.components as Record<string, unknown>).filter(
        (k) => !!(s.components as Record<string, unknown>)[k],
      );
    }

    // classes: string | string[] → string[] (lowercase for normalised lookup)
    let classes: string[] = [];
    if (Array.isArray(s.classes)) {
      classes = (s.classes as unknown[]).filter((c): c is string => typeof c === 'string');
    } else if (typeof s.classes === 'string') {
      classes = (s.classes as string)
        .split(',')
        .map((c) => c.trim())
        .filter(Boolean);
    }

    // description: string | string[] → string[]
    let description: string[] = [];
    if (typeof s.description === 'string') {
      description = s.description ? [s.description] : [];
    } else if (Array.isArray(s.description)) {
      description = (s.description as unknown[]).filter((d): d is string => typeof d === 'string');
    }

    return {
      id,
      name: (s.name as string) || `Unknown Spell ${i}`,
      level,
      school: (s.school as Spell['school']) || 'Evocation',
      castingTime: (s.castingTime as string) || 'Action',
      range: (s.range as string) || '60 feet',
      components: Object.freeze(components) as readonly string[],
      duration: (s.duration as string) || 'Instantaneous',
      concentration: !!s.concentration,
      ritual: !!s.ritual,
      description: Object.freeze(description) as readonly string[],
      source: (s.source as string) || 'SRD',
      ...(s.cantripUpgrade ? { cantripUpgrade: s.cantripUpgrade as readonly unknown[] } : {}),
      ...(s.damage ? { damage: s.damage as Record<string, unknown> } : {}),
      ...(s.save ? { save: s.save as Spell['save'] } : {}),
      ...(s.classes ? { classes: Object.freeze(classes) as readonly string[] } : {}),
    } as Spell;
  });
}

// Build and export the SRD content pack
export const srdContentPack: ContentPack = {
  meta: metaJson as unknown as ContentPack['meta'],
  species: speciesJson as unknown as ContentPack['species'],
  backgrounds: backgroundsJson as unknown as ContentPack['backgrounds'],
  classes: classesJson as unknown as ContentPack['classes'],
  subclasses: subclassesJson as unknown as ContentPack['subclasses'],
  feats: featsJson as unknown as ContentPack['feats'],
  weapons: weaponsJson as unknown as ContentPack['weapons'],
  armor: armorJson as unknown as ContentPack['armor'],
  gear: gearJson as unknown as ContentPack['gear'],
  spells: normaliseSpells(spellsJsonRaw),
  monsters: monstersJson as unknown as ContentPack['monsters'],
};
